name: Test

on:
  push:
    branches:
      - "**"
  pull_request:
    types: [ready_for_review, synchronize, opened]

jobs:
  tests-on-phpunit-9:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.1, 8.2, 8.3]
        testbench: [8.*]

    name: PHP:${{ matrix.php }} / Testbench:${{ matrix.testbench }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, iconv, intl, zip, pdo_sqlite
          tools: composer:v2
          coverage: none

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: dependencies-testbench-${{ matrix.testbench }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: dependencies-testbench-${{ matrix.testbench }}-php-${{ matrix.php }}-composer-

      - name: Install Composer dependencies
        run: |
          composer require "orchestra/testbench-dusk:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --prefer-stable --no-interaction --no-suggest

      - name: Setup dusk/chrome
        run: vendor/bin/dusk-updater detect --no-interaction

      - name: Run Browser tests
        run: vendor/bin/phpunit --testsuite Browser -c phpunit-9.xml.dist
        env:
          RUNNING_IN_CI: true

  tests-on-phpunit-10:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.1, 8.2]
        testbench: [8.*]

    name: PHP:${{ matrix.php }} / Testbench:${{ matrix.testbench }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, iconv, intl, zip, pdo_sqlite
          tools: composer:v2
          coverage: none

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: dependencies-testbench-${{ matrix.testbench }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: dependencies-testbench-${{ matrix.testbench }}-php-${{ matrix.php }}-composer-

      - name: Install Composer dependencies
        run: |
          composer require "orchestra/testbench-dusk:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --prefer-stable --no-interaction --no-suggest

      - name: Setup dusk/chrome
        run: vendor/bin/dusk-updater detect --no-interaction

      - name: Run Browser tests
        run: vendor/bin/phpunit --testsuite Browser -c phpunit.xml.dist
        env:
          RUNNING_IN_CI: true